blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/PH4rBdTU
    about: Use Discord for instantly connecting with other developers on this project.
  - name: Discussions
    url: https://github.com/agnyz/elysia-realworld-example-app/discussions
    about: Use GitHub discussions for a message board-style forum for the project, discussing ideas, questions, etc.
  - name: Q&A
    url: https://github.com/agnyz/elysia-realworld-example-app/discussions/categories/q-a?discussions_q=
    about: See the full list of questions and answers, or ask your own.